[package]
name = "ztp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ztp"
path = "bin/main.rs"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.12"
